---
- hosts: 127.0.0.1
  connection: local

  pre_tasks:
  - name: Update APT
    become: true
    apt:
      update_cache: yes
    
  - name: Configure Flatpak
    become: true
    community.general.flatpak_remote:
      name: flathub
      flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
    
  - name: Copy Assets
    copy:
      src: ./assets
      dest: /home/jaci/bootstrap
      owner: jaci
      group: jaci
      mode: '0644'

  roles:
    - { role: 'chrome', tags: 'chrome' }
    - { role: 'vscode', tags: 'vscode' }
    - { role: 'apt', tags: 'apt' }
    - { role: 'jabba', tags: 'jabba' }
    - { role: 'rust', tags: 'rust' }
    # Has some issues - certificate
    # - { role: 'rvm.ruby', 
    #     tags: 'ruby', 
    #     become: true, 
    #     rvm1_user: root, 
    #     rvm1_install_flags: '--auto-dotfiles',
    #     rvm1_install_path: /usr/local/rvm,
    #     rvm1_rubies: ['ruby-2.7.4']
    #   }
    - { role: 'nodejs', tags: 'nodejs' }
    - { role: 'recoll', tags: 'recoll' }
    - { role: 'nvim', tags: 'nvim' }
    - { role: 'docker', tags: 'docker' }
    - { role: 'oh-my-zsh', tags: 'zsh' }
    # Has some issues - pdflatex not on path
    # - { role: 'y-yu.texlive', tags: 'tex', become: true, scheme: full }
  
  tasks:
  - name: Apply dconf configuration
    shell: dconf load / < ./configs/dconf-settings.dconf
  
  - name: Install Simple Flatpaks
    become: true
    community.general.flatpak:
      name: "{{ item }}"
    loop:
      - com.spotify.Client
      - com.discordapp.Discord
      - org.zotero.Zotero
      - org.flameshot.Flameshot
      - org.speedcrunch.SpeedCrunch