---
- name: Check for Recoll
  command: dpkg-query -W recoll
  register: recoll_check
  failed_when: recoll_check.rc > 1
  changed_when: recoll_check.rc == 1

- name: Add Recoll APT Repository
  become: true
  ansible.builtin.apt_repository:
    repo: ppa:recoll-backports/recoll-1.15-on
  when: recoll_check.rc == 1
- name: Install recoll
  become: true
  ansible.builtin.apt:
    name: recoll
    update_cache: true
  when: recoll_check.rc == 1