---
- name: Install Vim Plug
  shell: curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  args:
    creates: '~/.vim/autoload/plug.vim'
  register: vim_plug

- name: Copy vimrc
  copy:
    src: ./configs/nvim/.vimrc
    dest: ~/.vimrc
  when: vim_plug.changed

- name: Copy nvim config
  copy:
    src: ./configs/nvim/nvim
    dest: ~/.config
  when: vim_plug.changed

- name: Vim Plug Install
  shell: vim +PlugInstall +qall
  when: vim_plug.changed